### PR TITLE
Support for Terminal.app templates

### PR DESCRIPTION
**Pull request by vbwx**
Since the PLIST profiles of Terminal.app are more complex than the profiles of iTerm2, I had to extend the Builder to correctly handle NSColor data.
Unfortunately, plutil needs to be in the PATH for this to work. If it can’t be found, the Terminal templates will be skipped.

### CODE REVIEW

**Comment by chriskempson** [comment]
Thanks for all the work but I'm afraid these changes would not be compatible with the current Builder Guidelines (https://github.com/chriskempson/base16/blob/master/builder.md). It's important that a Builder be kept as simple as possible and I don't think special exceptions to the guildelines should be added to accommodate applications that are problematic to generate theme files for.

**Comment by vbwx** [comment]
OK, I understand that.
But do you think it’s possible to add a link to my template/profiles, so Terminal users can find them when they want to install Base16 there, too? (see PR https://github.com/chriskempson/base16/pull/45)

**Comment by chriskempson** [comment]
Sure 😃 I think this PR would have been better as an issue raised on https://github.com/chriskempson/base16 just in case anyone else has something to say about this. I don't really like the idea of base16 becoming too limited with regards to the themes it can but I feel that there has to be a line to be drawn. For example I had the idea of base16 generating package files for Visual Studio Code and did create a branch for this but it felt like this kind of behaviour was going above and beyond simple templating.

**Comment by vbwx** [comment]
Thanks!
I agree – I'm gonna open an issue to leave this topic open for discussion.

**Pull request closed without merging**
